Building DAG of jobs...
Using shell: /anaconda2/envs/py3/bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	2	plot_background
	3	plot_background_kkclades
	6

[Wed Apr 17 11:51:51 2019]
rule plot_background_kkclades:
    input: dataframes/h3n2_ha_12y_fra.csv, config/clades_h3n2_ha.tsv
    output: plots/h3n2_ha_12y_fra/genetic_background_kkclade_heatmap_h3n2_ha_12y_fra.pdf
    jobid: 22
    wildcards: lineage=h3n2, segment=ha, resolution=12y, assay=fra

[Wed Apr 17 11:51:57 2019]
Finished job 22.
1 of 6 steps (17%) done

[Wed Apr 17 11:51:57 2019]
rule plot_background_kkclades:
    input: dataframes/h3n2_ha_6y_fra.csv, config/clades_h3n2_ha.tsv
    output: plots/h3n2_ha_6y_fra/genetic_background_kkclade_heatmap_h3n2_ha_6y_fra.pdf
    jobid: 20
    wildcards: lineage=h3n2, segment=ha, resolution=6y, assay=fra

[Wed Apr 17 11:52:02 2019]
Finished job 20.
2 of 6 steps (33%) done

[Wed Apr 17 11:52:02 2019]
rule plot_background:
    input: dataframes/h3n2_ha_6y_fra.csv, config/clades_h3n2_ha.tsv
    output: plots/h3n2_ha_6y_fra/genetic_background_heatmap_h3n2_ha_6y_fra.pdf
    jobid: 18
    wildcards: lineage=h3n2, segment=ha, assay=fra

Warning: the following output files of rule plot_background were not present when the DAG was created:
{'plots/h3n2_ha_6y_fra/genetic_background_heatmap_h3n2_ha_6y_fra.pdf'}
[Wed Apr 17 11:52:08 2019]
Finished job 18.
3 of 6 steps (50%) done

[Wed Apr 17 11:52:08 2019]
rule plot_background:
    input: dataframes/h3n2_ha_6y_hi.csv, config/clades_h3n2_ha.tsv
    output: plots/h3n2_ha_6y_hi/genetic_background_heatmap_h3n2_ha_6y_hi.pdf
    jobid: 17
    wildcards: lineage=h3n2, segment=ha, assay=hi

[Wed Apr 17 11:52:13 2019]
Error in rule plot_background:
    jobid: 17
    output: plots/h3n2_ha_6y_hi/genetic_background_heatmap_h3n2_ha_6y_hi.pdf

RuleException:
CalledProcessError in line 810 of /Users/katekistler/nextstrain/egg-passage/Snakefile:
Command 'set -euo pipefail;  python3 scripts/plot_background.py             --in_file dataframes/h3n2_ha_6y_hi.csv             --clades config/clades_h3n2_ha.tsv' returned non-zero exit status 1.
  File "/Users/katekistler/nextstrain/egg-passage/Snakefile", line 810, in __rule_plot_background
  File "/anaconda2/envs/py3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job plot_background since they might be corrupted:
plots/h3n2_ha_6y_hi/genetic_background_heatmap_h3n2_ha_6y_hi.pdf
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/katekistler/nextstrain/egg-passage/.snakemake/log/2019-04-17T115149.784133.snakemake.log
