Building DAG of jobs...
Using shell: /anaconda2/envs/py3/bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all_egg_analyses
	4	organize_output
	5

[Sat Mar  2 22:41:06 2019]
rule organize_output:
    input: auspice/flu_seasonal_h3n2_ha_12y_hi_tree.json, results/aa-seq_who_h3n2_ha_12y_concat_hi_HA1.fasta, auspice/flu_seasonal_h3n2_ha_12y_hi_root-sequence.json
    output: dataframes/h3n2_ha_12y_hi.csv, dataframes/h3n2_ha_12y_hi_egg.csv, dataframes/h3n2_ha_12y_hi_tidy.csv
    jobid: 3
    wildcards: lineage=h3n2, segment=ha, resolution=12y, assay=hi

[Sat Mar  2 22:41:06 2019]
Error in rule organize_output:
    jobid: 3
    output: dataframes/h3n2_ha_12y_hi.csv, dataframes/h3n2_ha_12y_hi_egg.csv, dataframes/h3n2_ha_12y_hi_tidy.csv

RuleException:
CalledProcessError in line 755 of /Users/katekistler/nextstrain/egg-passage/Snakefile:
Command 'set -euo pipefail;  python3 scripts/organize_output.py             --tree auspice/flu_seasonal_h3n2_ha_12y_hi_tree.json             --seqs results/aa-seq_who_h3n2_ha_12y_concat_hi_HA1.fasta             --root_seq auspice/flu_seasonal_h3n2_ha_12y_hi_root-sequence.json' returned non-zero exit status 1.
  File "/Users/katekistler/nextstrain/egg-passage/Snakefile", line 755, in __rule_organize_output
  File "/anaconda2/envs/py3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/katekistler/nextstrain/egg-passage/.snakemake/log/2019-03-02T224104.592742.snakemake.log
